"""Guards: user-facing text says 'Assist'; persistence keys/identifiers stay 'odysseus'."""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]


def _read(rel):
    return (ROOT / rel).read_text(encoding="utf-8")


def test_index_titles_say_assist():
    html = _read("static/index.html")
    assert "<title>Assist Chat</title>" in html
    assert "— Assist'" in html                 # route→title map entries
    assert "Message Assist..." in html          # composer placeholder
    assert ">Odysseus<" not in html             # no bare visible Odysseus label


def test_index_keeps_persistence_keys_and_identifiers():
    html = _read("static/index.html")
    assert "'odysseus-theme'" in html           # localStorage key preserved
    assert "odysseus-ui-scale" in html
    assert "_odysseusLoadTime" in html          # JS identifier preserved
    assert "odysseusInitMermaid" in html


def test_manifest_and_login_say_assist():
    man = _read("static/manifest.json")
    assert '"name": "Assist"' in man
    assert '"short_name": "Assist"' in man
    login = _read("static/login.html")
    assert "<title>Assist — Login</title>" in login
    assert "<span>Assist</span>" in login
    assert "'odysseus-theme'" in login          # login persistence key preserved


def test_report_template_says_assist():
    vr = _read("src/visual_report.py")
    assert "Assist &mdash; Deep Research Report" in vr
    assert "Generated by Assist Deep Research" in vr
