"""Guards: user-facing text says 'Assist'; persistence keys/identifiers stay 'odysseus'."""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]


def _read(rel):
    return (ROOT / rel).read_text(encoding="utf-8")


def test_index_titles_say_assist():
    html = _read("static/index.html")
    assert "<title>Assist Chat</title>" in html
    assert "— Assist'" in html                 # route→title map entries
    assert "Message Assist..." in html          # composer placeholder
    assert ">Odysseus<" not in html             # no bare visible Odysseus label


def test_index_keeps_persistence_keys_and_identifiers():
    html = _read("static/index.html")
    assert "'odysseus-theme'" in html           # localStorage key preserved
    assert "odysseus-ui-scale" in html
    assert "_odysseusLoadTime" in html          # JS identifier preserved
    assert "odysseusInitMermaid" in html


def test_manifest_and_login_say_assist():
    man = _read("static/manifest.json")
    assert '"name": "Assist"' in man
    assert '"short_name": "Assist"' in man
    login = _read("static/login.html")
    assert "<title>Assist — Login</title>" in login
    assert "<span>Assist</span>" in login
    assert "'odysseus-theme'" in login          # login persistence key preserved


def test_report_template_says_assist():
    vr = _read("src/visual_report.py")
    assert "Assist &mdash; Deep Research Report" in vr
    assert "Generated by Assist Deep Research" in vr


def test_readme_rebranded():
    r = _read("README.md")
    assert "docs/assist-wordmark.png" in r
    assert 'alt="Odysseus"' not in r
    assert "ASSIST_" in r  # env-var compatibility note mentions the new prefix


def test_dynamic_placeholder_says_assist():
    """app.js rewrites the composer placeholder on resize — it stomped the
    rebranded index.html value until 2026-07-08. Guard the JS layer too."""
    app = _read("static/app.js")
    assert "'Message Assist...'" in app
    assert "Message Odysseus" not in app


def test_no_stale_brand_strings_in_static_js():
    """User-visible brand strings across all frontend JS. The Odysseus
    *character* (presets.js prompt, tasks.js persona dropdown) and the
    /odyssey Homer quotes are intentionally exempt; comments/identifiers
    (startOdysseusApp, odysseus-theme keys) are not user-visible."""
    forbidden = ("Message Odysseus", "Odysseus Chat", "Odysseus Logo",
                 "Odysseus reminder emails", "Welcome to Odysseus",
                 "Odysseus Cookbook", "textContent = 'Odysseus'")
    hits = []
    for p in (ROOT / "static").rglob("*.js"):
        text = p.read_text(encoding="utf-8", errors="replace")
        hits += [f"{p.name}: {s}" for s in forbidden if s in text]
    assert not hits, f"stale Odysseus brand strings: {hits}"
